# Generated by Django 5.1 on 2024-08-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('published_date', models.DateField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('pages', models.IntegerField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('language', models.CharField(max_length=30)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(choices=[('FIC', 'Fiction'), ('NF', 'Non-Fiction'), ('MYS', 'Mystery'), ('SCI', 'Science Fiction'), ('FAN', 'Fantasy'), ('BIO', 'Biography'), ('HIS', 'History'), ('ROM', 'Romance'), ('THR', 'Thriller'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('copies', models.IntegerField(default=1)),
                ('rent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
    ]
