# Generated by Django 3.2.25 on 2024-09-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('FIC', 'Fiction'), ('NF', 'Non-Fiction'), ('MYS', 'Mystery'), ('SCI', 'Science Fiction'), ('FAN', 'Fantasy'), ('BIO', 'Biography'), ('HIS', 'History'), ('ROM', 'Romance'), ('THR', 'Thriller')], default='OTH', max_length=3),
        ),
    ]
