# Generated by Django 5.1 on 2024-08-25 13:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('books', '0002_alter_book_cover_alter_book_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_isbn', models.CharField(max_length=13)),
                ('rented_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField()),
                ('book_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
