# Generated by Django 3.2.25 on 2024-09-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rented_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentedbook',
            name='book_isbn',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='rentedbook',
            name='due_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
