# Generated by Django 3.2.25 on 2024-09-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rented_books', '0002_auto_20240926_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentedbook',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
