# Generated by Django 3.2.25 on 2024-09-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rented_books', '0003_rentedbook_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentedbook',
            name='cover_image',
        ),
    ]
